## CI for sr.ht

image: debian/unstable
arch: amd64
packages:
  - build-essential
  - libsqlite3-dev
tasks:
  - setup: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -sSf | sh -s -- -y
      . "$HOME/.cargo/env"
  - build: |
      cd last-location
      cargo build --verbose
  - build-doc: |
      cd last-location
      cargo doc --verbose
  - test: |
      cd last-location
      cargo test --verbose
